# Generated by Django 4.1.5 on 2023-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtsStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=30)),
                ("mat_number", models.CharField(max_length=12)),
                ("classe", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="EtsStudentPassWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStudent", models.IntegerField()),
                ("studentPassWordHashed", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SamissStudentPassWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStudent", models.IntegerField()),
                ("studentPassWordHashed", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SamisStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=30)),
                ("mat_number", models.CharField(max_length=12)),
                ("classe", models.CharField(max_length=3)),
            ],
        ),
    ]
