# Generated by Django 4.1.5 on 2023-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NombreABSPerModules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStudent", models.IntegerField()),
                ("mod202A", models.IntegerField()),
                ("mod216A", models.IntegerField()),
                ("mod214", models.IntegerField()),
                ("mod204", models.IntegerField()),
                ("messe", models.IntegerField()),
                ("mod213", models.IntegerField()),
                ("mod218", models.IntegerField()),
                ("mod212A", models.IntegerField()),
                ("mod209", models.IntegerField()),
                ("mod215", models.IntegerField()),
                ("mod203A", models.IntegerField()),
                ("mod207A", models.IntegerField()),
                ("mod222", models.IntegerField()),
                ("mod205", models.IntegerField()),
                ("mod201A", models.IntegerField()),
                ("formationhumaine", models.IntegerField()),
            ],
        ),
    ]
