# Generated by Django 4.1.5 on 2023-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="formationhumaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="idStudent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="messe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod201A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod202A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod203A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod204",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod205",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod207A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod209",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod212A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod213",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod214",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod215",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod216A",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod218",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nombreabspermodules",
            name="mod222",
            field=models.IntegerField(default=0),
        ),
    ]
