# Generated by Django 4.1.5 on 2023-02-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_alter_nombreabspermodules_formationhumaine_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="nombreabspermodules",
            table="nombreabspermodules",
        ),
    ]
