# Generated by Django 4.1.5 on 2023-02-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_alter_nombreabspermodules_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NombreABSPerModules",
            new_name="NombreABSPerModulesEts",
        ),
        migrations.AlterModelTable(
            name="nombreabspermodulesets",
            table="nombreabspermoduleets",
        ),
    ]
