# Generated by Django 4.1.5 on 2023-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtsABS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idStudent", models.IntegerField()),
                ("beginABS", models.DateTimeField()),
                ("endABS", models.DateTimeField()),
                ("motif", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=2)),
            ],
        ),
    ]
